// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://johmrxmmuwgtndvypjge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvaG1yeG1tdXdndG5kdnlwamdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxMDE2ODMsImV4cCI6MjA4NzY3NzY4M30.Z7-D6_i5CmtQ6Jcbv5qgvY_xYVIbqAZS9MP9-O_z90I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});